// constants.js
export const ZIMBABWE_CITIES = [
    "Harare",
    "Bulawayo",
    "Chitungwiza",
    "Mutare",
    "Epworth",
    "Gweru",
    "Kwekwe",
    "Kadoma",
    "Masvingo",
    "Chinhoyi",
    "Marondera",
    "Norton",
    "Chegutu",
    "Zvishavane",
    "Victoria Falls",
    "Hwange",
    "Redcliff",
    "Rusape",
    "Chiredzi",
    "Bindura",
    "Beitbridge",
    "Shurugwi",
    "Chipinge",
    "Kariba",
    "Karoi",
    "Gokwe",
    "Mvurwi",
    "Shamva",
    "Ruwa",
    "Nyanga",
    "Mazowe",
    "Chirundu",
    "Plumtree",
    "Mutoko",
    "Murewa",
    "Gwanda",
    "Binga",
    "Zaka",
    "Chimanimani",
    "Mvuradona",
    // Add more cities if needed
  ];
  